version: '3.8'

services:

  app:
    build:
      context: .
    ports:
      - 8090:80
    command: flask run -h 0.0.0.0 -p 8090

  nginx:
    image: nginx:1.19.3
    ports:
      - 8091:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
